{
 "title": "Monitor Main",
 "description": "Raspberry Pi Monitoring",
 "tags": [
  "influxdb",
  "telegraf",
  "raspberrypi",
  "pi4"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "rpi_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage %" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached,  mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS / PING MS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SD Card Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /8582c5a321d9$/ AND \"path\" =~ /^(\\/etc\\/hostname)$/ AND time >= now() - 30m GROUP BY time(30s), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "External HDD usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /8582c5a321d9$/ AND \"path\" =~ /^(\\/var\\/lib\\/grafana)$/AND time >= now() - 30m GROUP BY time(30s), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Context switches",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "pps", "label": "Drops per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Errors per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT non_negative_derivative(mean(\"in\")) as \"in\", non_negative_derivative(mean(\"out\")) as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}